# This Dockerfile is provided to tell which packages were installed.
FROM nvidia/cuda:10.0-cudnn7-devel

RUN apt-get update

# for opencv
RUN apt-get install -y libgtk2.0-dev libgl1-mesa-glx

# for openpose
RUN apt-get install -y libgflags-dev libgoogle-glog-dev liblmdb-dev \
libprotobuf-dev protobuf-compiler libhdf5-dev libatlas-base-dev libleveldb-dev libsnappy-dev

#for caffe
RUN apt-get install --no-install-recommends libboost-all-dev -y

# for python
RUN apt-get install -y python3-dev python3-pip
RUN python3 -m pip install --upgrade pip
RUN pip3 install numpy

